### ISSUE TITLE
License file rename (including .md extension)

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/alibi#14]
I meant to rename the `LICENSE` file in my own fork to `LICENSE.md`, to check whether GitHub would then pick up the file and mention on the front-page of the project what license is in use.

Instead, I mistakenly did the rename straight in the main project, see c754820. (Mea culpa! Will be more careul to work through my own fork for other things...)

The rename did have the desired effect, and the GitHub project now properly reports what license is in use. However, there might be a reason no extension was used before? If so we might need to undo the rename. Otherwise, perhaps I guess this issue could be closed? @FreekPaans probably knows?

**Comment by FreekPaans** [comment]
Strange, I seem to remember that Github did pick it up before. Anyway, I don't really care as long as it's clear what license is in use :)

However, when you open the file in Github now, formatting breaks. So we should either use a proper markdown file, or revert back to LICENSE.

**Comment by jeroenheijmans** [comment]
Good point, not thought about that. I'll experiment on a personal fork to see how this can be fixed, and then properly fix this. Perhaps `.txt` works too? Will check if there's documentation on GitHub somewhere...
